Initial renovate config based on modified dubbd renovate.json
defenseunicorns/uds-capability-gitlab pull request #16
Opened 2023-07-25 19:48 UTC by jacobbmay

PR setting up renovate. Used renovate.json from uds-package-dubbd as a starting point.

2023-07-25 19:52 UTC, jacobbmay commented on Makefile
>  DUBBD_K3D_VERSION := 0.5.0
Where to renovate this from?

2023-07-25 19:58 UTC, corang commented on Makefile
>  DUBBD_K3D_VERSION := 0.5.0
here https://github.com/defenseunicorns/uds-package-dubbd/pkgs/container/packages%2Fdubbd-k3d

2023-07-25 20:02 UTC, corang requested changes

2023-07-25 20:02 UTC, corang commented on .github/workflows/publish.yml
>            uri: 'https://github.com/defenseunicorns/zarf/releases/download/v0.28.0/zarf_v0.28.0_Linux_amd64'
The URI has to be renovated as well. See my repo here https://github.com/corang/uds-package-dubbd-kind/blob/main/renovate.json#L80-L103

2023-07-25 20:02 UTC, corang commented on values-gitlab.yaml
None of the istioversion needs to be renovated, this file just needs to be cleaned up

2023-07-25 20:02 UTC, corang commented on zarf.yaml
> +    # renovate: datasource=docker
I wonder if there's a better way to do this?

2023-07-25 20:04 UTC, anthonywendt commented on test/values-gitlab.yaml
>        namespace: gitlab
This entire file can be deleted. We only need the values file at the top level of the repo.

2023-07-27 15:59 UTC, jacobbmay commented on zarf.yaml
> +    # renovate: datasource=docker
@corang I agree the current solution isn't very elegant with a large list of images like this. I tried using this regex for the pattern to match everything in the images list: https://regex101.com/r/UyiotK/1

Unfortunately renovate uses re2 which doesn't support backreferences or lookaheads so the \G and \K make the regex invalid for renovate.

Haven't found a way to match the list of images without using the backreference characters.

2023-07-27 16:14 UTC, jacobbmay commented on zarf.yaml
> +    # renovate: datasource=docker
Here is a simpler option, but it doesn't restrict matching to lines after the "images" key so there is more potential for it to match something it shouldn't: https://regex101.com/r/JQpUoB/1

Not sure if you can think of any cases where that would cause an issue.

2023-07-27 18:00 UTC, jacobbmay commented on zarf.yaml
> +    # renovate: datasource=docker
Went with the second simpler option. Let me know if you can think of any future issues with that pattern.

2023-07-27 19:19 UTC, corang approved these changes
Looks alright to me

2023-07-27 19:20 UTC, corang commented
Don't worry about the required check, just let me know when it's ready and I'll merge it

2023-07-27 19:29 UTC, merged