Upped dubbd to 0.12.0
defenseunicorns/uds-capability-gitlab pull request #46
Opened 2023-11-02 23:51 UTC by Michael-Kruggel

2023-11-02 23:51 UTC, Michael-Kruggel commented
/test all

2023-11-03 14:07 UTC, blancharda requested changes
Let's chat about upgrade paths..
I think we're going to need an 0.11.* release as well.

2023-11-03 15:03 UTC, blancharda commented on Makefile
> +DUBBD_K3D_VERSION := 0.12.0
I think I've been talked off the cliff..

2023-11-03 16:07 UTC, Michael-Kruggel commented
/test all

2023-11-03 17:38 UTC, Michael-Kruggel commented
/test all

2023-11-03 18:10 UTC, corang approved these changes

2023-11-03 18:10 UTC, merged